# Generated by Django 6.0.3 on 2026-03-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='DjangoModel',
        ),
    ]
