# Generated by Django 6.0.3 on 2026-03-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuApp', '0007_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cook_prep_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
