# Generated by Django 6.0.3 on 2026-03-31 16:25

import re

from django.db import migrations, models


def sync_existing_prep_values(apps, schema_editor):
    Order = apps.get_model("MenuApp", "Order")
    for order in Order.objects.all():
        if order.cook_prep_time:
            match = re.search(r"(\d+)", order.cook_prep_time)
            if match:
                order.cook_prep_minutes = int(match.group(1))
        if order.status == "cooking":
            order.status = "preparing"
        order.save(update_fields=["cook_prep_minutes", "status"])


class Migration(migrations.Migration):

    dependencies = [
        ("MenuApp", "0008_order_cook_prep_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cook_extra_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="cook_prep_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("preparing", "Preparation started"),
                    ("ready", "Ready for pickup"),
                    ("completed", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.RunPython(sync_existing_prep_values, migrations.RunPython.noop),
    ]
