# Generated by Django 6.0.3 on 2026-04-22 06:48

import django.db.models.deletion
from django.db import migrations, models
from decimal import Decimal, InvalidOperation
import re


def normalize_menu_prices(apps, schema_editor):
    MenuItem = apps.get_model("MenuApp", "MenuItem")
    for item in MenuItem.objects.all().only("id", "price"):
        raw_price = str(item.price or "").strip()
        cleaned_price = re.sub(r"[^\d.]", "", raw_price)

        if cleaned_price.count(".") > 1:
            first, *rest = cleaned_price.split(".")
            cleaned_price = f"{first}.{''.join(rest)}"

        try:
            normalized = Decimal(cleaned_price or "0").quantize(Decimal("0.01"))
        except InvalidOperation:
            normalized = Decimal("0.00")

        item.price = f"{normalized:.2f}"
        item.save(update_fields=["price"])


class Migration(migrations.Migration):

    dependencies = [
        ('MenuApp', '0011_alter_menuitem_image'),
    ]

    operations = [
        migrations.RunPython(normalize_menu_prices, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=30)),
                ('provider_event_id', models.CharField(max_length=120, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('payment_id', models.CharField(blank=True, max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='processed', max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_events', to='MenuApp.order')),
            ],
            options={
                'ordering': ['-processed_at'],
                'indexes': [models.Index(fields=['provider', 'event_type'], name='MenuApp_pay_provide_d9638d_idx'), models.Index(fields=['order', 'processed_at'], name='MenuApp_pay_order_i_86acf5_idx')],
            },
        ),
    ]
