# Generated by Django 6.0.4 on 2026-04-23 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuApp', '0013_order_confirmed_at_order_payment_due_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='full_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='half_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='portion',
            field=models.CharField(choices=[('full', 'Full'), ('half', 'Half')], default='full', max_length=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='MenuApp.menuitem'),
        ),
    ]
