from django.urls import path
from . import views

urlpatterns = [
    path('',views.home_view, name='home_view'),
    path('health/', views.healthcheck_view, name='healthcheck_view'),
    path('contact/',views.contact_view, name='contact_view'),
    path('services/',views.services_view, name='services_view'),
    path('api/v1/auth/signup/', views.jwt_signup_view, name='jwt_signup_view_v1'),
    path('api/v1/auth/login/', views.jwt_login_view, name='jwt_login_view_v1'),
    path('api/v1/auth/refresh/', views.jwt_refresh_view, name='jwt_refresh_view_v1'),
    path('api/v1/auth/me/', views.jwt_me_view, name='jwt_me_view_v1'),
    path('api/v1/auth/logout/', views.jwt_logout_view, name='jwt_logout_view_v1'),
    path('api/v1/menu/', views.menu_api_view, name='menu_api_view_v1'),
    path('api/v1/menu/<int:item_id>/', views.menu_detail_api_view, name='menu_detail_api_view_v1'),
    path('api/v1/orders/', views.my_orders_api_view, name='my_orders_api_view_v1'),
    path('api/v1/orders/<int:order_id>/status/', views.order_status_api_view, name='order_status_api_view_v1'),
    path('api/v1/payments/razorpay/order/', views.razorpay_order_api_view, name='razorpay_order_api_view_v1'),
    path('api/v1/payments/razorpay/webhook/', views.razorpay_webhook_view, name='razorpay_webhook_view_v1'),
    path('api/auth/signup/', views.jwt_signup_view, name='jwt_signup_view'),
    path('api/auth/login/', views.jwt_login_view, name='jwt_login_view'),
    path('api/auth/refresh/', views.jwt_refresh_view, name='jwt_refresh_view'),
    path('api/auth/me/', views.jwt_me_view, name='jwt_me_view'),
    path('api/auth/logout/', views.jwt_logout_view, name='jwt_logout_view'),
    path('api/menu/', views.menu_api_view, name='menu_api_view'),
    path('api/menu/<int:item_id>/', views.menu_detail_api_view, name='menu_detail_api_view'),
    path('api/orders/', views.my_orders_api_view, name='my_orders_api_view'),
    path('api/orders/<int:order_id>/status/', views.order_status_api_view, name='order_status_api_view'),
    path('api/payments/razorpay/order/', views.razorpay_order_api_view, name='razorpay_order_api_view'),
    path('payments/razorpay/order/', views.razorpay_order_session_view, name='razorpay_order_session_view'),
    path('menu/',views.menu_view, name='menu_view'),
    path('cart/',views.cart_view, name='cart_view'),
    path('order/',views.order_view, name='order_view'),
    path('orders/', views.my_orders_view, name='my_orders_view'),
    path('orders/<int:order_id>/', views.order_detail_view, name='order_detail_view'),
    path('orders/<int:order_id>/payment-action/', views.order_payment_action_view, name='order_payment_action_view'),
    path('orders/<int:order_id>/items/<int:item_id>/rate/', views.order_item_rating_view, name='order_item_rating_view'),
    path('profile/',views.profile_view, name='profile_view'),
    path('logout/',views.logout_view, name='logout_view'),
    path('cook/orders/', views.cook_orders_view, name='cook_orders_view'),
    path('cook/orders/history/', views.cook_order_history_view, name='cook_order_history_view'),
]
